### ISSUE TITLE
Segfault on llsf_refbox_comm plugin 

### ISSUE THREAD

**Issue by ValentinVERGEZ** [robocup-logistics/gazebo-rcll#1]
Hi guys ! 

We (the French PYRO Team) are trying to connect the simulation with our ROS nodes and  the refereebox, but we encouter a segfault on start of llsf_refbox_comm plugin.

Do you have the same problem ?

**Comment by zwilling** [comment]
Hi,
We don't have that problem. So, your Gazebo has a segfault when you load a world with the llsf_refbox_comm plugin and it does work when you comment out the plugin in the world file, right?
Can you tell me, where the segfault happens in the code? Do you have the refbox running when you start gazebo? If Yes, did you merge the timn/rcll-2015 branch in the refbox and did you check the llsf-refbox/cfg/config.yaml file? I think you can see how we configured the refbox for the simulation here: https://trac.fawkesrobotics.org/wiki/Carologistics/Gazsim-Setup-2015

**Comment by ValentinVERGEZ** [comment]
Hi,

> We don't have that problem. So, your Gazebo has a segfault when you load a world with the llsf_refbox_comm plugin and it does work when you comment out the plugin in the world file, right?

Right.

We have a refbox running. We merged the timn/rcll2015 and checked the llsf-refbox/cfg/config.yaml file. The SegFault happens in ProtobufStreamClient::ProtobufStreamClient() constructor.

We use Gazebo 2 (integrated with ROS Indigo).

Since your answer, I tried with Gazebo 5 (integrated with ROS Jade) and it works ! So, I think I will probably adapt our codes for ROS Jade, but it could be useful to mention the minimal version of Gazebo needed in the README.

**Comment by GeraldSteinbauer** [comment]
in graz we have the same issue - any solution except changing the simulator and ros version ?

**Comment by zwilling** [comment]
No known solution yet, but I might be able to help you if you give me a backtrace. I am also not sure what another Gazebo or ROS version would change in the ProtobufStreamClient constructor. Maybe a simple 'make clean; make all' solves the issue. Do you use the master branch and are the Protobuf messages build (plugins/src/libs/*_msgs)?

**Comment by GeraldSteinbauer** [comment]
it seams to be a kind of threading problem 

in order to debug I changed the code

ProtobufStreamClient::ProtobufStreamClient(MessageRegister *mr,
					   frame_header_version_t header_version)
  : message_register_(mr), own_message_register_(false),
    frame_header_version_(header_version)
{
  printf("io_service_ 3\n"); 
  io_service_ = new boost::asio::io_service();
  printf("resolver_\n");
  resolver_ = new boost::asio::ip::tcp::resolver(*io_service_);
  printf("socket_\n");
  socket_ = new boost::asio::ip::tcp::socket(*io_service_);
  printf("io_service_work_\n");
  io_service_work_ = new boost::asio::io_service::work(*io_service_);
  printf("open socket\n");
  connected_ = false;
  outbound_active_ = false;
  in_data_size_ = 1024;
  in_data_ = malloc(in_data_size_);
  if (frame_header_version_ == PB_FRAME_V1) {
    in_frame_header_size_ = sizeof(frame_header_v1_t);
  } else {
    in_frame_header_size_ = sizeof(frame_header_t);
  }
  in_frame_header_ = malloc(in_frame_header_size_);
  run_asio();
}

socket_ = new boost::asio::ip::tcp::socket(*io_service_); causes the segfault

if I use -O0 the error occurs later in the connect

working on a backtrace - not so simple with gazebo

**Comment by vmatare** [comment]
I ran into a similar error at a similar location, and it turned out to be a compiler bug in GCC 5.4. Didn't dig much deeper after I found that it works after compiling everything with GCC 6...
